apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: nexa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rahulgowda526/nexa-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: nexa-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: nexa-config
                  key: DB_PORT
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nexa-db-secret
                  key: DB_PASSWORD 
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nexa-config
                  key: DB_NAME