name: NEXA Dashboard CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nexa-backend:latest ./backend

      - name: Build Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nexa-frontend:latest ./frontend

      - name: Push Backend Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nexa-backend:latest

      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nexa-frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/nexa-dashboard && \
            git pull origin main && \
            docker-compose pull && \
            docker-compose down && \
            docker-compose up -d
